UC-Web/src/main/java/com/mariusiliescu/spring/model/entities/Companie.java
package com.mariusiliescu.spring.model.entities;

import java.util.ArrayList;
import java.util.Collection;
import javax.persistence.Column;
import javax.persistence.Embedded;
import javax.persistence.Entity;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

import com.mariusiliescu.spring.model.entities.persoane.Client;


@Entity
@Table(name= "Companie")
@PrimaryKeyJoinColumn(name="id_client")
public class Companie extends Client {
	
	@Column(unique=true)
	private String cui;
	
	private String numeC;
	private String eMail;
	
	@Embedded
	private Adresa adresaC;
	private String nrTelefonC;
	
	public Companie(TipClient tipClient, String cui, String numeC, String eMail, Adresa adresaC,
			String nrTelefonC) {
		this.cui = cui;
		this.numeC = numeC;
		this.eMail = eMail;
		this.adresaC = adresaC;
		this.nrTelefonC = nrTelefonC;
		this.listaFacturi = new ArrayList<Factura>();
	}
	
	public Companie() {
		this.cui = new String();
		this.numeC = new String();
		this.eMail = new String();
		this.adresaC = new Adresa();
		this.nrTelefonC = new String();
	}


	public String getCui() {
		return cui;
	}


	public void setCui(String cui) {
		this.cui = cui;
	}


	public String getNumeC() {
		return numeC;
	}


	public void setNumeC(String numeC) {
		this.numeC = numeC;
	}


	public String geteMail() {
		return eMail;
	}


	public void seteMail(String eMail) {
		this.eMail = eMail;
	}


	public Adresa getAdresaC() {
		return adresaC;
	}


	public void setAdresaC(Adresa adresaC) {
		this.adresaC = adresaC;
	}


	public String getNrTelefonC() {
		return nrTelefonC;
	}


	public void setNrTelefonC(String nrTelefonC) {
		this.nrTelefonC = nrTelefonC;
	}

	@Override
	public String getNume() {
		return this.numeC;
	}

	@Override
	public String getPassword() {
		return this.cui.substring(cui.length()-6, cui.length());
	}

	@Override
	public Collection<Factura> getListaFacturi() {
		return this.listaFacturi;
	}

	@Override
	public void adaugareFactura(Factura f) {
		this.listaFacturi.add(f);
	}

	@Override
	public String getSSNCUI() {
		return cui;
	}
		
}

UC-Web/src/main/java/com/mariusiliescu/spring/controller/HomeController.java
package com.mariusiliescu.spring.controller;

import java.text.DateFormat;
import java.util.Date;
import java.util.Locale;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

/**
 * Handles requests for the application home page.
 */
@Controller
public class HomeController {
	
	private static final Logger logger = LoggerFactory.getLogger(HomeController.class);
	
	/**
	 * Simply selects the home view to render by returning its name.
	 */
	@RequestMapping(value = "/", method = RequestMethod.GET)
	public String home(Locale locale, Model model) {
		logger.info("Welcome home! The client locale is {}.", locale);
		
		Date date = new Date();
		DateFormat dateFormat = DateFormat.getDateTimeInstance(DateFormat.LONG, DateFormat.LONG, locale);
		
		String formattedDate = dateFormat.format(date);
		
		model.addAttribute("serverTime", formattedDate );
		
		return "home";
	}
	
}

UC-Web/src/main/java/com/mariusiliescu/spring/controller/LoginController.java
package com.mariusiliescu.spring.controller;

import java.util.Map;
import java.util.concurrent.atomic.AtomicInteger;

import javax.servlet.http.HttpSession;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import com.mariusiliescu.spring.model.entities.persoane.Client;
import com.mariusiliescu.spring.model.service.ClientService;

@Controller
public class LoginController {

	@Autowired
	private ClientService customerService;
	
	
	@RequestMapping(value = "/login", method = RequestMethod.GET)
	public String showLoginForm() {
		return "login";
	}
	
	@RequestMapping(value = "/home", method = RequestMethod.GET)
	public String showHomeForm() {
		return "home";
	}
	

	@RequestMapping(value = "/login", method = RequestMethod.POST)
    public String verifyLogin(@RequestParam String userId, 
    		@RequestParam String password, HttpSession session, Model model) {
        
		//customerService.adaugareFacturi();
		
		//Client customer = customerService.loginClient(userId, password);
		Client customer = customerService.getTmpClient();
		if (customer == null) {
			model.addAttribute("loginError", "Error logging in. Please try again");
			return "login";
		}
		session.setAttribute("loggedInUser", customer);
		
        return "redirect:home";
    }
	
	@RequestMapping(value = "/logout", method = RequestMethod.GET)
	public String logout(HttpSession session) {
		session.removeAttribute("loggedInUser");
		return "redirect:login";
	}
}

UC-Web/src/main/webapp/WEB-INF/views/home.jsp
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ page session="true"%>
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
	pageEncoding="ISO-8859-1"%>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags"%>
<!DOCTYPE html>
<html>

<head>

<style type="text/css">
#parent {
	display: flex;
}

#narrow {
	width: 400px;
	background: lightblue;
	/* Just so it's visible */
}

#wide {
	margin-right: 20px;
	margin-left: 20px;
	flex: 1;
}

body {
	margin: 40px;
}
</style>

<link href='http://fonts.googleapis.com/css?family=Oswald:400,300'
	rel='stylesheet'>
<link href="resources/css/style.css" rel="stylesheet">
<script src="https://maps.googleapis.com/maps/api/js?v=3"
	type="text/javascript"></script>
<script type='text/javascript' src='resources/js/map.js'></script>
<script type='text/javascript'
	src='http://code.jquery.com/jquery-2.0.2.js'></script>
<link rel="stylesheet"
	href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<script
	src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"
	type="text/javascript"></script>
<script
	src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"
	type="text/javascript"></script>
</head>
<body>
	<div class="header">
		<div class="container">
			<div class="login" style="width: 200px;">
				<c:choose>
					<c:when test="${empty loggedInUser.numeC }">
						<a href="login" class="btn btn-default btn-sm"> <span
							class="glyphicon glyphicon-log-in"></span> Log in
						</a>
					</c:when>

					<c:otherwise>
						<div>
							<b>Hello : </b> ${loggedInUser.numeC} <br /> <b>CUI:</b>
							${loggedInUser.cui}! &nbsp;
							<form action="logout">
								<a href="logout" class="btn btn-default btn-sm"> <span
									class="glyphicon glyphicon-log-out"></span> Log out
								</a>
							</form>
							<br />
						</div>
					</c:otherwise>
				</c:choose>
			</div>
			<a href="#" class="logo-icon"> <img
				src="https://peli-pod.com/media/1027/courier-icon-green.png?width=150px&amp;height=150px"
				alt="">
			</a>
			<ul class="menu">
				<li><a href="#">Descarca Aplicatia</a></li>
				<li><a href="#">Detalii de facturare</a></li>
				<li><a href="#">Lista sediilor</a></li>
				<li><a href="#">Call center</a></li>
				<li class="dropdown"><a href="#" class="dropdown-toggle">Mai
						multe<b class="caret"></b>
				</a>
					<ul class="dropdown-menu">
						<li><a href="#">Ceva</a></li>
						<li><a href="#">Altceva</a></li>
						<li><a href="#">Evenimente</a></li>
						<li><a href="#">Despre Noi</a></li>
					</ul></li>
			</ul>
		</div>
	</div>
	<br />
	<br />
	<br />
	<div>
		<c:choose>
			<c:when test="${empty loggedInUser.numeC }" />



			<c:otherwise>
				<div id="parent">
					<div id="wide">
						<c:if test="${empty loggedInUser.listaFacturi}">
								You don't have any orders
							</c:if>
						<c:if test="${ not empty loggedInUser.listaFacturi}">
							<h2>Comenzile male</h2>
							<table id="myTable" class="table table-hover">
								<thead>
									<tr>
										<th>#Factura</th>
										<th>Valoare Totala</th>
										<th>Discount %</th>
										<th>Intemeietor</th>
										<td>Numar Produse</td>
										<th>Data preluare</th>
										<th>Data expediere</th>
										<th>Detalii Comanda</th>
									</tr>
								</thead>
								<tbody>
									<c:forEach var="fact" items="${loggedInUser.listaFacturi}">
										<tr>
											<td>${fact.codFactura}</td>
											<td>${fact.valoareEfectiva}</td>
											<td>${fact.valoareDiscount*100}</td>
											<td><p>${fact.intemeietor.nume}   ${fact.intemeietor.prenume}</p></td>
											<td>${fact.comanda.numarProduse}</td>
											<td>${fact.comanda.dataPreluare}</td>
											<td>${fact.comanda.dataExpediere}</td>
											<td>
												<ol>
													<c:forEach var="pac" items="${fact.comanda.listaPachete}">
														<p>${pac}</p>
													</c:forEach>
												</ol>
											</td>
											<td><a href="#" class="btn btn-default btn-sm"
												data-toggle="modal" data-target="#myModal"> <span
													class="glyphicon glyphicon-duplicate"></span> Vezi factura
											</a></td>
										</tr>

									</c:forEach>
								</tbody>
							</table>

						</c:if>
					</div>
					<div id="narrow">
						<iframe
							src="https://www.facebook.com/plugins/page.php?href=https%3A%2F%2Fwww.facebook.com%2Ffacebook&amp;tabs=timeline&amp;width=400&amp;height=700&amp;small_header=false&amp;adapt_container_width=true&amp;hide_cover=false&amp;show_facepile=true&amp;appId"
							width="400" height="700" style="border: none; overflow: hidden"
							scrolling="no" frameborder="0" allowTransparency="true"></iframe>
					</div>

				</div>
			</c:otherwise>
		</c:choose>
	</div>

	<br />
	<br />
	<br />
	<br />
	<br />
	<br />
	<div id="sliders">
		<div class="slider">

			<div class="slide active-slide">
				<div class="container">
					<div class="row">
						<div class="slide-copy col-xs-5">
							<h1>Descarca aplicatia UcExpress</h1>
							<p>UcExpress este o aplicatie care urmeaza a fi dezvoltata de
								catre Marius Iliescu , atunci cand va avea timp si mai ales
								chef.</p>

							<ul class="get-app">
								<li><a href="#"><img
										src="http://s3.amazonaws.com/codecademy-content/courses/ltp2/img/flipboard/ios.png"
										alt=""></a></li>
								<li><a href="#"><img
										src="http://s3.amazonaws.com/codecademy-content/courses/ltp2/img/flipboard/android.png"
										alt=""></a></li>
								<li><a href="#"><img
										src="http://s3.amazonaws.com/codecademy-content/courses/ltp2/img/flipboard/windows.png"
										alt=""></a></li>
								<li><a href="#"><img
										src="http://s3.amazonaws.com/codecademy-content/courses/ltp2/img/flipboard/blackberry.png"
										alt=""></a></li>
							</ul>
						</div>
						<div class="slide-img col-xs-7">
							<img
								src="https://7labs.heypub.com/wp-content/uploads/2015/03/Track-shipment-status-automatically-from-iPhone-Android.png"
								width="540px" alt="">
						</div>
					</div>
				</div>
			</div>

			<div class="slide slide-feature">
				<div class="container">
					<div class="row">
						<div class="col-xs-12">
							<a href="#">Citeste Acum</a>
						</div>

					</div>
				</div>
			</div>

			<div class="slide">
				<div class="container">
					<div class="row">
						<div class="slide-copy col-xs-5">
							<h1>Preturi avantajoase</h1>
							<h2>-cele mai mici-</h2>
							<p>Daca gasiti in alta parte mai ieftin ducetiva acolo.</p>

						</div>
						<div class="slide-img col-xs-7">
							<img
								src="https://paceaustralia.files.wordpress.com/2012/07/price-cut.jpg"
								alt="">
						</div>
					</div>
				</div>
			</div>

			<div class="slide">
				<div class="container">
					<div class="row">
						<div class="slide-copy col-xs-5">
							<h1>Suntem peste tot</h1>
							<p>Ne gasiti la urmatoarele locatii in fiecare zi de luni
								pana duminica intre orele 08:00-22:00</p>
						</div>
						<div class="slide-img col-xs-7">
							<div id ="googleMap" style="width:700px;height:420px;">
						</div>
					</div>
				</div>
			</div>
		</div>


		<div class="slide">
			<div class="container">
				<div class="row">
					<div class="slide-copy col-xs-5">
						<h1>Curierat simpu si rapid</h1>
						<p>Mi de oameni din toate colturile tarii au beneficiat de
							serviciile noastre.</p>

					</div>
					<div class="slide-img col-xs-7">
						<img
							src="http://blog.tjobs.ro/blog/wp-content/uploads/2014/03/c4736dc935c189544aebb6f51b9f219f-600x300.jpg"
							width="540px" alt="">
					</div>
				</div>
			</div>
		</div>

	</div>

	<div class="slider-nav">
		<a class="arrow-prev"><img
			src="http://s3.amazonaws.com/codecademy-content/courses/ltp2/img/flipboard/arrow-prev.png"
			alt=""></a>
		<ul class="slider-dots">
			<li class="dot active-dot">&bull;</li>
			<li class="dot">&bull;</li>
			<li class="dot">&bull;</li>
			<li class="dot">&bull;</li>
			<li class="dot">&bull;</li>
		</ul>
		<a id="slideb" class="arrow-next"><img
			src="http://s3.amazonaws.com/codecademy-content/courses/ltp2/img/flipboard/arrow-next.png"
			alt=""></a>
	</div>
	</div>



	<!-- Modal -->
	<div class="modal fade" id="myModal" role="dialog">
		<div class="modal-dialog">

			<!-- Modal content-->
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal">&times;</button>
					<h4 class="modal-title">Factura</h4>
				</div>
				<div class="modal-body">
					<p>Factura ..... I don't know .... am pierdut-o . :)</p>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
				</div>
			</div>

		</div>
	</div>

	<script src="https://code.jquery.com/jquery-2.1.4.min.js"
		type="text/javascript"></script>
	<script src="resources/js/app.js" type="text/javascript"></script>
	<footer>
		<p>Made by Marius Iliescu</p>
		<p>
			Contact information: <a href="mailto:iliescu.marius.a@gmail.com">iliescu.marius.a@gmail.com</a>.
		</p>
	</footer>

	<script type="text/javascript">
		var timer = null;
		$('#sliders').hover(function(ev) {
			clearInterval(timer);
		}, function(ev) {
			timer = setInterval(function() {
				document.getElementById("slideb").click();
			}, 3000);
		});
	</script>
</body>
</html>

UC-Web/src/main/webapp/WEB-INF/views/login.jsp
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ page session="true"%>
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>    
<!DOCTYPE html>
<html>
<head>
    <link href='http://fonts.googleapis.com/css?family=Oswald:400,300' rel='stylesheet'>
    <link href="http://s3.amazonaws.com/codecademy-content/courses/ltp2/css/bootstrap.min.css" rel="stylesheet">
    <link href="resources/css/style.css" rel="stylesheet">
    <script src="https://maps.googleapis.com/maps/api/js?v=3"></script>
	<script type='text/javascript'src='resources/js/map.js'></script>
  </head>
  <body>
    <div class="header">
      <div class="container">
        <div class="login" style="width:200px;">
			<form action='login' method="post" >
				<div >
					<input type="text" id="userId" name="userId" placeholder="Id-ul de client" class="form-control"/>
				</div>
				
				<div>
					<input type="password" id="password" name="password" placeholder="CNP-ul sau CUI-ul" class="form-control"/>
				</div>
				<button id="loginButton" class="form-control">Login</button>
			</form>
		</div>
		<a href="#" class="logo-icon">
          <img src="https://peli-pod.com/media/1027/courier-icon-green.png?width=150px&height=150px">
        </a>
        <ul class="menu">
          <li><a href="#">Descarca Aplicatia</a></li>
          <li><a href="#">Detalii de facturare</a></li>
          <li><a href="#">Lista sediilor</a></li>
          <li><a href="#">Call center</a></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle">Mai multe<b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><a href="#">Ceva</a></li>
              <li><a href="#">Altceva</a></li>
              <li><a href="#">Evenimente</a></li>
              <li><a href="#">Despre Noi</a></li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
    
    <div>
    	<c:choose>
				<c:when test="${empty loggedInUser.numeC }">
					
				</c:when>

				<c:otherwise>
					<div>
						<c:if test="${empty loggedInUser.listaFacturi}">
							You don't have any orders
						</c:if>
						<c:if test="${ not empty loggedInUser.listaFacturi}">
							<h4>Order list</h4>
							<ul >
								<c:forEach var="fact" items="${loggedInUser.listaFacturi}">
									<li class = "factura">
										<p><b>Cod factura : </b>${fact.codFactura} ; </p>
										<p><b>Valoare Totala : </b>${fact.valoareTotala} ;</p>
										<p><b>Intemeietor: </b>${fact.intemeietor.nume} ;</p>
										<p><b>Comanda : </b>${fact.comanda}</p>
										<p><b>Lista de pachete</b></p>
										<c:forEach var="pac" items="${fact.comanda.listaPachete}">
											<p>${pac}</p>
										</c:forEach>

									</li>

								</c:forEach>
							</ul>
						</c:if>
					</div>
				</c:otherwise>
			</c:choose>
    </div>
	<div id = "sliders">
		<div class="slider">

		  <div class="slide active-slide">
			<div class="container">
			  <div class="row">
				<div class="slide-copy col-xs-5">
				  <h1>Descarca aplicatia UcExpress</h1>
				  <p>UcExpress este o aplicatie care urmeaza a fi dezvoltata de catre Marius Iliescu , atunci cand va avea timp si mai ales chef.</p>
				  
				  <ul class="get-app">
					<li><a href="#"><img src="http://s3.amazonaws.com/codecademy-content/courses/ltp2/img/flipboard/ios.png"></a></li>
					<li><a href="#"><img src="http://s3.amazonaws.com/codecademy-content/courses/ltp2/img/flipboard/android.png"></a></li>
					<li><a href="#"><img src="http://s3.amazonaws.com/codecademy-content/courses/ltp2/img/flipboard/windows.png"></a></li>
					<li><a href="#"><img src="http://s3.amazonaws.com/codecademy-content/courses/ltp2/img/flipboard/blackberry.png"></a></li>
				  </ul>
				</div>
				<div class="slide-img col-xs-7">
				  <img src="https://7labs.heypub.com/wp-content/uploads/2015/03/Track-shipment-status-automatically-from-iPhone-Android.png" width="540px">
				</div>
			  </div>
			</div>      
		  </div>

		  <div class="slide slide-feature">
			<div class="container">
			  <div class="row">
				<div class="col-xs-12">
				  <a href="#">Citeste Acum</a>
				</div>
				
			  </div>
			</div>      
		  </div> 

		  <div class="slide">
			<div class="container">
			  <div class="row">
				<div class="slide-copy col-xs-5">
				  <h1>Preturi avantajoase</h1>
				  <h2>-cele mai mici-</h2>
				  <p>Daca gasiti in alta parte mai ieftin ducetiva acolo.</p>
				  
				</div>
				<div class="slide-img col-xs-7">
				  <img src="https://paceaustralia.files.wordpress.com/2012/07/price-cut.jpg">
				</div>
			  </div>
			</div>      
		  </div> 
		  
		  <div class="slide">
			<div class="container">
			  <div class="row">
				<div class="slide-copy col-xs-5">
				  <h1>Suntem peste tot</h1>
				  <p>Ne gasiti la urmatoarele locatii in fiecare zi de luni pana duminica intre orele 08:00-22:00 </p>
				  
				</div>
				<br/>
				<div id="googleMap" style="width:700px;height:420px;"></div>
			  </div>
			</div>      
		  </div> 


		  <div class="slide">
			<div class="container">
			  <div class="row">
				<div class="slide-copy col-xs-5">
				  <h1>Curierat simpu si rapid</h1>
				  <p>Mi de oameni din toate colturile tarii au beneficiat de serviciile noastre.</p>
				  
				</div>
				<div class="slide-img col-xs-7">
				  <img src="http://blog.tjobs.ro/blog/wp-content/uploads/2014/03/c4736dc935c189544aebb6f51b9f219f-600x300.jpg" width="540px">
				</div>
			  </div>
			</div>      
		  </div> 

		</div>

		<div class="slider-nav">
		  <a href="#" class="arrow-prev"><img src="http://s3.amazonaws.com/codecademy-content/courses/ltp2/img/flipboard/arrow-prev.png"></a>
		  <ul class="slider-dots">
			<li class="dot active-dot">&bull;</li>
			<li class="dot">&bull;</li>
			<li class="dot">&bull;</li>
			<li class="dot">&bull;</li>
			<li class="dot">&bull;</li>
		  </ul>
		  <a href="#"id = "slideb" class="arrow-next"><img src="http://s3.amazonaws.com/codecademy-content/courses/ltp2/img/flipboard/arrow-next.png"></a>
		</div> 
	</div>
    
    <script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>    
    <script src="resources/js/app.js"></script>
    <footer>
	  <p>Made by Marius Iliescu</p>
	  <p>Contact information: <a href="mailto:iliescu.marius.a@gmail.com">iliescu.marius.a@gmail.com</a>.</p>
	</footer>
	
	<script>
	var timer = null;
	$('#sliders').hover(function(ev){
		clearInterval(timer);
	}, function(ev){
		timer = setInterval(function () {document.getElementById("slideb").click();}, 3000);
	});
	</script>
  </body>
</html>

UC-Web/src/main/webapp/WEB-INF/views/view.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<title>View Profile</title>
<jsp:include page="/WEB-INF/views/include/head-include.jsp" />
</head>
<body>
<%


%>

<div class="container">
	<h2>View Profile</h2>
	<div> Name:</div>
	<div> ${user.firstName} ${user.lastName} </div>
	<div> Email: </div>
	<div> ${user.email}</div>
</div>
</body>
</html>